name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["2.7", "3.11"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install"
        run: |
          set -xe
          python -m pip install --editable .
      - name: "Run tests for ${{ matrix.python-version }}"
        run: python -m pytest
      - name: "Run mypy checks for ${{ matrix.python-version }}"
        run: |
          python -m pip install mypy==1.4.1
          python -m mypy pytest_structlog
      - name: "Run mypy install checks for ${{ matrix.python-version }}"
        run: |
          # This checks that things like the py.typed bits work
          cd tests
          python -m pip install ..
          python -m mypy .
