name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install --editable . --config-settings editable_mode=strict

      - name: Run tests for ${{ matrix.python-version }}
        run: pytest

      - name: Run mypy checks for ${{ matrix.python-version }}
        run: |
          pip install mypy
          mypy pytest_structlog

      - uses: jakebailey/pyright-action@v2
        with:
          ignore-external: true
          verify-types: pytest_structlog

  check-package:
    name: Build & inspect our package.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2
